<a href="https://colab.research.google.com/github/husky2212/AWS-recoknition-real-time/blob/master/covidessentials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing pandas module 
import pandas as pd 
  
# making data frame from csv file 
data = pd.read_csv("CMOHistoricalDataMonthly.csv" ) 

df1 = data.iloc[5:]
  
# dropping passed columns 
  
# display /
new_header = df1.iloc[0] #grab the first row for the header
df1 = df1[1:] #take the data less the header row
df1.columns = new_header #set
df1.reset_index(drop=True, inplace=True)
df1['month'] = df1['month'].str.replace('M', '')

df1.head()
5	month	CRUDE_PETRO	CRUDE_BRENT	CRUDE_DUBAI	CRUDE_WTI	COAL_AUS	COAL_SAFRICA	NGAS_US	NGAS_EUR	NGAS_JP	...	COAL_COL	COPRA	iSTL_JP_INDX	STL_JP_CROLL	STL_JP_HROLL	STL_JP_REBAR	STL_JP_WIROD	COTTON_MEMPH	RUBBER1_US	WHEAT_CANADI
0	196001	1.63	..	1.63	..	..	..	0.14	0.4	..	...	..	257	..	..	..	..	..	..	..	64
1	196002	1.63	..	1.63	..	..	..	0.14	0.4	..	...	..	248	..	..	..	..	..	..	..	64.09
2	196003	1.63	..	1.63	..	..	..	0.14	0.4	..	...	..	236	..	..	..	..	..	..	..	63.76
3	196004	1.63	..	1.63	..	..	..	0.14	0.4	..	...	..	214	..	..	..	..	..	..	..	63.35
4	196005	1.63	..	1.63	..	..	..	0.14	0.4	..	...	..	206	..	..	..	..	..	..	..	63.11
5 rows × 83 columns

df1 = df1.drop(df1.index[0:714])
df1
5	month	CRUDE_PETRO	CRUDE_BRENT	CRUDE_DUBAI	CRUDE_WTI	COAL_AUS	COAL_SAFRICA	NGAS_US	NGAS_EUR	NGAS_JP	...	COAL_COL	COPRA	iSTL_JP_INDX	STL_JP_CROLL	STL_JP_HROLL	STL_JP_REBAR	STL_JP_WIROD	COTTON_MEMPH	RUBBER1_US	WHEAT_CANADI
714	2019-07	61.48	64	62.91	57.52	72.08	65.79	2.36	3.62	10.13	...	..	..	..	..	..	..	..	..	..	..
715	2019-08	57.67	59.25	58.92	54.84	65.55	60.43	2.22	3.68	10.86	...	..	..	..	..	..	..	..	..	..	..
716	2019-09	60.04	62.33	60.84	56.95	65.95	61.37	2.58	4.21	10.14	...	..	..	..	..	..	..	..	..	..	..
717	2019-10	57.27	59.37	58.47	53.98	69.2	67.44	2.33	5.06	9.98	...	..	..	..	..	..	..	..	..	..	..
718	2019-11	60.4	62.74	61.41	57.06	66.99	73.62	2.65	5.15	10.04	...	..	..	..	..	..	..	..	..	..	..
719	2019-12	63.35	65.85	64.41	59.8	66.18	76.03	2.24	4.62	10.06	...	..	..	..	..	..	..	..	..	..	..
720	2020-01	61.63	63.6	63.76	57.52	69.66	82.09	2.03	3.63	9.89	...	..	..	..	..	..	..	..	..	..	..
721	2020-02	53.35	55	54.51	50.53	67.64	79.99	1.92	2.91	9.89	...	..	..	..	..	..	..	..	..	..	..
722	2020-03	32.2	32.98	33.75	29.88	66.74	67.89	1.79	2.72	10.21	...	..	..	..	..	..	..	..	..	..	..
723	2020-04	21.04	23.34	23.27	16.52	58.55	56.58	1.74	2.12	10.21	...	..	..	..	..	..	..	..	..	..	..
10 rows × 83 columns

df1.reset_index(drop=True, inplace=True)
import datetime
df1['year'] = pd.DatetimeIndex(df1['month']).year
df1['months'] = pd.DatetimeIndex(df1['month']).month
import calendar
df1['months'] = df1['months'].apply(lambda x: calendar.month_abbr[x])
df1
5	month	CRUDE_PETRO	CRUDE_BRENT	CRUDE_DUBAI	CRUDE_WTI	COAL_AUS	COAL_SAFRICA	NGAS_US	NGAS_EUR	NGAS_JP	...	iSTL_JP_INDX	STL_JP_CROLL	STL_JP_HROLL	STL_JP_REBAR	STL_JP_WIROD	COTTON_MEMPH	RUBBER1_US	WHEAT_CANADI	year	months
0	2019-07	61.48	64	62.91	57.52	72.08	65.79	2.36	3.62	10.13	...	..	..	..	..	..	..	..	..	2019	Jul
1	2019-08	57.67	59.25	58.92	54.84	65.55	60.43	2.22	3.68	10.86	...	..	..	..	..	..	..	..	..	2019	Aug
2	2019-09	60.04	62.33	60.84	56.95	65.95	61.37	2.58	4.21	10.14	...	..	..	..	..	..	..	..	..	2019	Sep
3	2019-10	57.27	59.37	58.47	53.98	69.2	67.44	2.33	5.06	9.98	...	..	..	..	..	..	..	..	..	2019	Oct
4	2019-11	60.4	62.74	61.41	57.06	66.99	73.62	2.65	5.15	10.04	...	..	..	..	..	..	..	..	..	2019	Nov
5	2019-12	63.35	65.85	64.41	59.8	66.18	76.03	2.24	4.62	10.06	...	..	..	..	..	..	..	..	..	2019	Dec
6	2020-01	61.63	63.6	63.76	57.52	69.66	82.09	2.03	3.63	9.89	...	..	..	..	..	..	..	..	..	2020	Jan
7	2020-02	53.35	55	54.51	50.53	67.64	79.99	1.92	2.91	9.89	...	..	..	..	..	..	..	..	..	2020	Feb
8	2020-03	32.2	32.98	33.75	29.88	66.74	67.89	1.79	2.72	10.21	...	..	..	..	..	..	..	..	..	2020	Mar
9	2020-04	21.04	23.34	23.27	16.52	58.55	56.58	1.74	2.12	10.21	...	..	..	..	..	..	..	..	..	2020	Apr
10 rows × 85 columns

df1 = df1.drop(columns="month")
df1['period'] = df1["months"]+ "-" + df1["year"].map(str)
df1 = df1.drop(['CRUDE_BRENT', 'CRUDE_DUBAI','COAL_SAFRICA','NGAS_US','NGAS_EUR','NGAS_JP','COCOA','COFFEE_ARABIC','COFFEE_ROBUS','TEA_COLOMBO','TEA_KOLKATA','TEA_MOMBASA','COPRA','iSTL_JP_INDX','STL_JP_CROLL','STL_JP_HROLL','STL_JP_REBAR','COTTON_MEMPH','RUBBER1_US','FISH_MEAL','GRNUT_OIL','PALM_OIL','Tin','NICKEL','Zinc','PLATINUM','SILVER','COAL_COL','STL_JP_WIROD','WHEAT_CANADI','COCONUT_OIL','PLMKRNL_OIL','SOYBEAN_OIL','DAP','TSP','UREA_EE_BULK','POTASH','ALUMINUM','COPPER','LEAD','SOYBEAN_MEAL','RAPESEED_OIL','SUNFLOWER_OIL','SAWNWD_MYS','PLYWOOD','WOODPULP','COTTON_A_INDX','RUBBER_TSR20','LOGS_CMR','LOGS_MYS','SAWNWD_CMR','LOGS_MYS','MAIZE','SORGHUM','LAMB','SHRIMP_MEX','SUGAR_EU','SUGAR_US','BARLEY','ORANGE','RICE_05','BEEF','RUBBER1_MYSG','PHOSROCK','RICE_A1','RICE_05_VNM','WHEAT_US_SRW','BANANA_EU','IRON_ORE','CRUDE_WTI'], axis = 1) 
df1.rename(columns={"GOLD": "gold($/troy oz)","CRUDE_PETRO": "petrol($/bbl)", "COAL_AUS": "coal($/mt)","iNATGAS": "gas","TEA_AVG": "tea($/kg)","GRNUT": "groundnut($/mt)","RICE_25": "rice($/mt)","WHEAT_US_HRW": "wheat($/mt)","BANANA_US": "banana($/kg)","SUGAR_WLD": "sugar($/kg)","TOBAC_US": "tobacco($/mt)","SOYBEANS": "soyabeans($/kg)","CHICKEN": "chicken($/kg)"})
5	petrol($/bbl)	coal($/mt)	gas	tea($/kg)	groundnut($/mt)	soyabeans($/kg)	rice($/mt)	wheat($/mt)	banana($/kg)	chicken($/kg)	sugar($/kg)	tobacco($/mt)	gold($/troy oz)	year	months	period
0	61.48	72.08	52.73	2.64	1260	369.58	409	196.21	1.13	1.99	0.28	4541.98	1412.89	2019	Jul	Jul-2019
1	57.67	65.55	51.85	2.63	1252.38	360.93	421	181.15	1.12	1.9	0.27	4522.48	1500.41	2019	Aug	Aug-2019
2	60.04	65.95	58.19	2.54	1321.43	366.07	421	189.6	1.15	1.85	0.26	4543.84	1510.58	2019	Sep	Sep-2019
3	57.27	69.2	59.12	2.58	1358.7	381.65	418	199.52	1.13	1.85	0.28	4446.9	1494.81	2019	Oct	Oct-2019
4	60.4	66.99	63.47	2.6	1400	375.51	415	203.19	1.13	1.85	0.28	4316.86	1470.79	2019	Nov	Nov-2019
5	63.35	66.18	56.01	2.57	1528.75	383.2	423	210.91	1.15	1.98	0.3	4316.44	1479.13	2019	Dec	Dec-2019
6	61.63	69.66	48.63	2.51	1671.59	387.23	440	224.5	1.17	2.07	0.31	4420.08	1560.67	2020	Jan	Jan-2020
7	53.35	67.64	43.79	2.35	1718.75	375.63	442	215.32	1.18	1.88	0.33	4698.49	1597.1	2020	Feb	Feb-2020
8	32.2	66.74	41.61	2.19	1868.18	372.29	477	209.07	1.2	1.8	0.26	4686.85	1591.93	2020	Mar	Mar-2020
9	21.04	58.55	38.11	2.19	2050	361.26	536	218.99	1.28	1.27	0.23	4660.78	1683.17	2020	Apr	Apr-2020
#df1['groundnut($/mt)']= df1['groundnut($/mt)'].div(1000)
#df1
#df1['groundnut($/mt)']= df1['groundnut($/mt)'].apply(lambda x: x /1000)
#df1
df1.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 16 columns):
CRUDE_PETRO     10 non-null object
COAL_AUS        10 non-null object
iNATGAS         10 non-null object
TEA_AVG         10 non-null object
GRNUT           10 non-null object
SOYBEANS        10 non-null object
RICE_25         10 non-null object
WHEAT_US_HRW    10 non-null object
BANANA_US       10 non-null object
CHICKEN         10 non-null object
SUGAR_WLD       10 non-null object
TOBAC_US        10 non-null object
GOLD            10 non-null object
year            10 non-null int64
months          10 non-null object
period          10 non-null object
dtypes: int64(1), object(15)
memory usage: 1.4+ KB
cols = df1.columns.drop('period')

df1[cols] = df1[cols].apply(pd.to_numeric, errors='coerce')
df1 = df1.rename(columns={"GOLD": "gold(rs/gram)","CRUDE_PETRO": "crude petrol(rs/l)", "COAL_AUS": "coal(rs/kg)","iNATGAS": "gas","TEA_AVG": "tea($/kg)","GRNUT": "groundnut(rs/kg)","RICE_25": "rice(rs/kg)","WHEAT_US_HRW": "wheat(rs/kg)","BANANA_US": "banana(rs/kg)","SUGAR_WLD": "sugar(rs/kg)","TOBAC_US": "tobacco(rs/kg)","SOYBEANS": "soyabeans(rs/kg)","CHICKEN": "chicken(rs/kg)"})
df1
5	crude petrol(rs/l)	coal(rs/kg)	gas	tea($/kg)	groundnut(rs/kg)	soyabeans(rs/kg)	rice(rs/kg)	wheat(rs/kg)	banana(rs/kg)	chicken(rs/kg)	sugar(rs/kg)	tobacco(rs/kg)	gold(rs/gram)	year	months	period
0	61.48	72.08	52.73	2.64	1260.00	369.58	409	196.21	1.13	1.99	0.28	4541.98	1412.89	2019	NaN	Jul-2019
1	57.67	65.55	51.85	2.63	1252.38	360.93	421	181.15	1.12	1.90	0.27	4522.48	1500.41	2019	NaN	Aug-2019
2	60.04	65.95	58.19	2.54	1321.43	366.07	421	189.60	1.15	1.85	0.26	4543.84	1510.58	2019	NaN	Sep-2019
3	57.27	69.20	59.12	2.58	1358.70	381.65	418	199.52	1.13	1.85	0.28	4446.90	1494.81	2019	NaN	Oct-2019
4	60.40	66.99	63.47	2.60	1400.00	375.51	415	203.19	1.13	1.85	0.28	4316.86	1470.79	2019	NaN	Nov-2019
5	63.35	66.18	56.01	2.57	1528.75	383.20	423	210.91	1.15	1.98	0.30	4316.44	1479.13	2019	NaN	Dec-2019
6	61.63	69.66	48.63	2.51	1671.59	387.23	440	224.50	1.17	2.07	0.31	4420.08	1560.67	2020	NaN	Jan-2020
7	53.35	67.64	43.79	2.35	1718.75	375.63	442	215.32	1.18	1.88	0.33	4698.49	1597.10	2020	NaN	Feb-2020
8	32.20	66.74	41.61	2.19	1868.18	372.29	477	209.07	1.20	1.80	0.26	4686.85	1591.93	2020	NaN	Mar-2020
9	21.04	58.55	38.11	2.19	2050.00	361.26	536	218.99	1.28	1.27	0.23	4660.78	1683.17	2020	NaN	Apr-2020
df1['coal(rs/kg)']= df1['coal(rs/kg)'].div(1000)
df1['crude petrol(rs/l)']= df1['crude petrol(rs/l)'].div(158)
df1['gold(rs/gram)']= df1['gold(rs/gram)'].mul(2.42)
df1['soyabeans(rs/kg)']= df1['soyabeans(rs/kg)'].div(1000)
df1['rice(rs/kg)']= df1['rice(rs/kg)'].div(1000)
df1['wheat(rs/kg)']= df1['wheat(rs/kg)'].div(1000)
df1['tobacco(rs/kg)']= df1['tobacco(rs/kg)'].div(1000)
df1['groundnut(rs/kg)']= df1['groundnut(rs/kg)'].div(1000)
df1 = df1.drop('gas' , axis = 1)
df1 = df1.drop('months' , axis = 1)
df1.iloc[:,:11] = df1.iloc[:,:11] * 75.52

df1
5	crude petrol(rs/l)	coal(rs/kg)	tea($/kg)	groundnut(rs/kg)	soyabeans(rs/kg)	rice(rs/kg)	wheat(rs/kg)	banana(rs/kg)	chicken(rs/kg)	sugar(rs/kg)	tobacco(rs/kg)	gold(rs/gram)	year	period
0	29.385884	5.443482	199.3728	95.155200	27.910682	30.88768	14.817779	85.3376	150.2848	21.1456	343.010330	3419.1938	2019	Jul-2019
1	27.564800	4.950336	198.6176	94.579738	27.257434	31.79392	13.680448	84.5824	143.4880	20.3904	341.537690	3630.9922	2019	Aug-2019
2	28.697600	4.980544	191.8208	99.794394	27.645606	31.79392	14.318592	86.8480	139.7120	19.6352	343.150797	3655.6036	2019	Sep-2019
3	27.373610	5.225984	194.8416	102.609024	28.822208	31.56736	15.067750	85.3376	139.7120	21.1456	335.829888	3617.4402	2019	Oct-2019
4	28.869671	5.059085	196.3520	105.728000	28.358515	31.34080	15.344909	85.3376	139.7120	21.1456	326.009267	3559.3118	2019	Nov-2019
5	30.279696	4.997914	194.0864	115.451200	28.939264	31.94496	15.927923	86.8480	149.5296	22.6560	325.977549	3579.4946	2019	Dec-2019
6	29.457580	5.260723	189.5552	126.238477	29.243610	33.22880	16.954240	88.3584	156.3264	23.4112	333.804442	3776.8214	2020	Jan-2020
7	25.499949	5.108173	177.4720	129.800000	28.367578	33.37984	16.260966	89.1136	141.9776	24.9216	354.829965	3864.9820	2020	Feb-2020
8	15.390785	5.040205	165.3888	141.084954	28.115341	36.02304	15.788966	90.6240	135.9360	19.6352	353.950912	3852.4706	2020	Mar-2020
9	10.056587	4.421696	165.3888	154.816000	27.282355	40.47872	16.538125	96.6656	95.9104	17.3696	351.982106	4073.2714	2020	Apr-2020
df1 = df1.drop("gold(rs/gram)", axis=1)
before_corona = df1.iloc[:6]
before_corona
5	crude petrol(rs/l)	coal(rs/kg)	tea($/kg)	groundnut(rs/kg)	soyabeans(rs/kg)	rice(rs/kg)	wheat(rs/kg)	banana(rs/kg)	chicken(rs/kg)	sugar(rs/kg)	tobacco(rs/kg)	year	period
0	29.385884	5.443482	199.3728	95.155200	27.910682	30.88768	14.817779	85.3376	150.2848	21.1456	343.010330	2019	Jul-2019
1	27.564800	4.950336	198.6176	94.579738	27.257434	31.79392	13.680448	84.5824	143.4880	20.3904	341.537690	2019	Aug-2019
2	28.697600	4.980544	191.8208	99.794394	27.645606	31.79392	14.318592	86.8480	139.7120	19.6352	343.150797	2019	Sep-2019
3	27.373610	5.225984	194.8416	102.609024	28.822208	31.56736	15.067750	85.3376	139.7120	21.1456	335.829888	2019	Oct-2019
4	28.869671	5.059085	196.3520	105.728000	28.358515	31.34080	15.344909	85.3376	139.7120	21.1456	326.009267	2019	Nov-2019
5	30.279696	4.997914	194.0864	115.451200	28.939264	31.94496	15.927923	86.8480	149.5296	22.6560	325.977549	2019	Dec-2019
after_corona = df1.loc[df1['year'] > 2019]
after_corona
5	crude petrol(rs/l)	coal(rs/kg)	tea($/kg)	groundnut(rs/kg)	soyabeans(rs/kg)	rice(rs/kg)	wheat(rs/kg)	banana(rs/kg)	chicken(rs/kg)	sugar(rs/kg)	tobacco(rs/kg)	year	period
6	29.457580	5.260723	189.5552	126.238477	29.243610	33.22880	16.954240	88.3584	156.3264	23.4112	333.804442	2020	Jan-2020
7	25.499949	5.108173	177.4720	129.800000	28.367578	33.37984	16.260966	89.1136	141.9776	24.9216	354.829965	2020	Feb-2020
8	15.390785	5.040205	165.3888	141.084954	28.115341	36.02304	15.788966	90.6240	135.9360	19.6352	353.950912	2020	Mar-2020
9	10.056587	4.421696	165.3888	154.816000	27.282355	40.47872	16.538125	96.6656	95.9104	17.3696	351.982106	2020	Apr-2020
import matplotlib.pyplot as plt
import pandas as pd

# gca stands for 'get current axis'
ax = plt.gca()

before_corona.plot(kind='line',x='period',y='crude petrol(rs/l)',ax=ax)
before_corona.plot(kind='line',x='period',y='coal(rs/kg)', color='red', ax=ax)
before_corona.plot(kind='line',x='period',y='tea($/kg)',ax=ax)
before_corona.plot(kind='line',x='period',y='groundnut(rs/kg)',ax=ax)
before_corona.plot(kind='line',x='period',y='soyabeans(rs/kg)',ax=ax)
before_corona.plot(kind='line',x='period',y='rice(rs/kg)',ax=ax)
before_corona.plot(kind='line',x='period',y='wheat(rs/kg)',ax=ax)
before_corona.plot(kind='line',x='period',y='banana(rs/kg)',ax=ax)
before_corona.plot(kind='line',x='period',y='chicken(rs/kg)',ax=ax)
before_corona.plot(kind='line',x='period',y='sugar(rs/kg)',ax=ax)
before_corona.plot(kind='line',x='period',y='tobacco(rs/kg)',ax=ax)
plt.title('BEFORE CORONAVIRUS')

plt.ylabel('values in rupees per kg/l')


plt.gcf().set_size_inches(15,15)

from this result we can observe
from this above plot we easily observe tabacco price is declining with time and all other food items with crude and coal are almost constant throughout 6 months before corona virus except groundnut price which increased till December 2019.

import matplotlib.pyplot as plt
import pandas as pd
# gca stands for 'get current axis'
ax = plt.gca()

after_corona.plot(kind='line',x='period',y='crude petrol(rs/l)',ax=ax)
after_corona.plot(kind='line',x='period',y='coal(rs/kg)', color='red', ax=ax)
after_corona.plot(kind='line',x='period',y='tea($/kg)',ax=ax)
after_corona.plot(kind='line',x='period',y='groundnut(rs/kg)',ax=ax)
after_corona.plot(kind='line',x='period',y='soyabeans(rs/kg)',ax=ax)
after_corona.plot(kind='line',x='period',y='rice(rs/kg)',ax=ax)
after_corona.plot(kind='line',x='period',y='wheat(rs/kg)',ax=ax)
after_corona.plot(kind='line',x='period',y='banana(rs/kg)',ax=ax)
after_corona.plot(kind='line',x='period',y='chicken(rs/kg)',ax=ax)
after_corona.plot(kind='line',x='period',y='sugar(rs/kg)',ax=ax)
after_corona.plot(kind='line',x='period',y='tobacco(rs/kg)',ax=ax)
plt.title('AFTER CORONAVIRUS')
plt.ylabel('values in rupees per kg/l')




plt.gcf().set_size_inches(15,15)

from this result we can observe
from this above plot we hereby observe tabacco, groundnut, banana and rice prices rose and chicken, tea, and crude oil sales went down drastically during conovirus spread.